name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy when pushing to main

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: portfolio_VO

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build static site with Next.js
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Must match `output: 'export'`
          publish_branch: gh-pages
          cname: www.shardul-deshmukh.com  # remove if you're not using a custom domain
